package com.bank.islamic.islamicfxwadarrangements;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Islamic FX Wad Arrangements
 *
 * Business Area:      Treasury Markets and Sukuk
 * Business Domain:    Islamic Treasury
 * Functional Pattern: Process
 * Asset Type:         Wad FX Arrangement
 * Control Record:     Wad FX Arrangement Procedure
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Islamic FX Wad Arrangements — BIAN Semantic API")
                .description("Service Domain 'Islamic FX Wad Arrangements' (Process pattern) "
                        + "operating on the 'Wad FX Arrangement Procedure' control record.")
                .version("0.1.0"));
    }
}
